//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zadanie3
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public string ProductArticleNumber { get; set; }
        public string Наименование { get; set; }
        public string Единица_измерения { get; set; }
        public Nullable<int> Стоимость { get; set; }
        public string Производитель { get; set; }
        public string Поставщик { get; set; }
        public string Категория_товара { get; set; }
        public Nullable<int> Скидка { get; set; }
        public Nullable<int> Кол_склад { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
        public Nullable<int> Макс_скидка { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }

        public string PhotoFull
        {
            get
            {
                if(this.Изображение == "")
                    return "\\Image\\" + "picture.png";
                else
                {
                    string namePhoto =  "\\Image\\" + Изображение;
                    return namePhoto;
                }

            }
        }
    }

    
}
